permalink: /:year/:month/:day/:title.html
paginate: 10





# 作者信息
author: 
  name: Yongchun Wang 
  email: ycwang_1@outlook.com
  weibo: http://weibo.com/u/2996503952
  github: http://github.com/ycwang522
  music: http://music.163.com/#/user/home?id=60616754
  csdn：http://blog.csdn.net/wyc12306

# 站点信息
title: 小栈
description: My Private Website
url: http://ycwang522.github.io/
# url_tags必须和tags.md中的permalink定义相同，这样定义的原因是不希望permalink中包含文件类型后缀。
# 或者tags.md中不定义permalink，这里直接引用tags.md的在目录中的绝对地址。
# 其它几个url也需要遵循这个原则。
url_rss:            /pages/atom.xml
url_about:          /pages/about.html
url_archives:       /pages/archive.html
url_atom:           /pages/atom.html

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-78088304-1
  url: http://ycwang522.github.io/

# disqus 设置
disqus:
  shortname: ycwang522

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档


# markdown设置
# redcarpet extensions 含义参考 https://github.com/vmg/redcarpet
# 选择它的主要原因是，支持```language```语法，用来标记代码块，不需要缩进4个空格。
# 另外还支持脚注、文本高亮、删除线等扩展的markdown语法，
# 需要加入extensions列表才能开启或关闭相应功能。
# 
# 表格语法需要特别注意 :-: 中间若有空格，可能不会解析。
# no_intra_emphasis: do not parse emphasis inside of words 不解析单词间的下划线
# 
# 其它可选的markdown: rdiscount, kramdown, 
#
# Github 不再支持 redcarpet， 替换为 kramdown
# https://github.com/planetjekyll/quickrefs/blob/master/FAQ.md#q-how-can-i-get-backtick-fenced-code-blocks-eg--working-with-kramdown
#
# Should the markdown renderer treat a single line break as <br>?
# http://meta.stackexchange.com/questions/26011/should-the-markdown-renderer-treat-a-single-line-break-as-br
#
# Markdown 需要敲两次回车才能产生一个新的段落。
# 仅仅一个回车不会被解释为换行，如果想换行，需要在行尾「敲两个空格然后回车」，或者在行尾加标签 <br>，或者设置 hard_wrap 为 true
#
# http://kramdown.gettalong.org/rdoc/Kramdown/Options.html
# hard_wrap=true  Interprets line breaks literally

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true

# Fixing highlighting errors: pygments not supported.

highlighter: rouge
    



include: []
exclude: ["README.md"]


# For jekyll-3.0
gems: [jekyll-paginate]
