permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

<!--
# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed
//-->


# 作者信息
author: 
  name: Yongchun Wang 
  email: ycwang_1@outlook.com
  weibo: http://weibo.com/u/2996503952
  github: http://github.com/ycwang522
  music: http://music.163.com/#/user/home?id=60616754

# 站点信息
title: 小站
description: My Private Website
url: http://ycwang522.github.io/
#rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-78088304-1
  url: http://ycwang522.github.io/

# disqus 设置
disqus:
  shortname: ycwang522

# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
