permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Yongchun Wang 
  email: ycwang_1@outlook.com
#  link: http://painterlin.com
  weibo: http://weibo.com/u/2996503952
  github: http://github.com/ycwang522
  music: http://music.163.com/#/user/home?id=60616754
#  linkedin: https://www.linkedin.com/pub/anya-lin/81/91/232

# 站点信息
title: 小站
description: My Private Website
url: http://ycwang522.github.io/
#rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics 设置
ga:
  id: UA-78088304-1
  url: http://ycwang522.github.io/

# disqus 设置
disqus:
  shortname: ycwang522

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
